version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      # nginx配置文件
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl
      - ./www:/var/www/
    networks:
      - backend
    environment:
      - TZ=Asia/Shanghai
    links: 
      - php82

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./www/certbot/:/var/www/certbot/:rw
      - ./nginx/ssl/:/etc/letsencrypt/:rw
    networks:
      - backend
    environment:
      - TZ=Asia/Shanghai

  php82:
    build:
      context: ./php82
    container_name: php82
    restart: always
    volumes:
      # php 配置文件
      - ./php82/etc/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php82/etc/conf.d/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini:ro
      - ./php82/etc/php-fpm.d:/usr/local/etc/php-fpm.d:ro
      # 项目代码
      - ./www:/var/www/
    networks:
      - backend
    environment:
      - TZ=Asia/Shanghai
    links: 
      - mysql
      - redis
    
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - TZ=Asia/Shanghai
    volumes:
      # 数据文件
      - ./mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always   
    networks:
      - backend

  redis:
    image: redis:latest
    restart: always
    networks:
      - backend
    environment:
      - TZ=Asia/Shanghai


networks:
  backend: